### ISSUE TITLE
Issues with validation when using Terraform v0.12.20+ and installing with `go get`

### ISSUE THREAD

**Issue by migueleliasweb** [flosell/iam-policy-json-to-terraform#9] opened 2020-03-30 05:26 UTC
The current output looks like:

```hcl
data "aws_iam_policy_document" "policy" {
  statement = [
    {
      sid       = ""
      effect    = "Allow"
      resources = ["arn:aws:dynamodb:ap-southeast-2:<account-id>:table/<redacted>"]

      actions = [
        "dynamodb:GetItem",
        "dynamodb:PutItem",
        "dynamodb:DeleteItem",
        "dynamodb:Scan",
        "dynamodb:GetRecords",
        "dynamodb:DescribeTable",
        "dynamodb:DescribeStream",
        "dynamodb:GetShardIterator",
        "dynamodb:ListStreams",
        "dynamodb:Query",
      ]
   }
]
```

But Terraform v0.12.20+ complains about the `statement` during the validation step (`terraform validate`). I had to convert each item to the list to multiple references of `statement` to make it work.

The error:
```
An argument named "statement" is not expected here. Did you mean to define a block of type "statement"?
```

**Comment by flosell** [comment] 2020-03-30 13:51
Thanks for reporting this! Just to confirm that I understand you correctly: 
When you call `iam-policy-json-to-terraform` with your policy-json, the output you are getting contains ` statement = [`? 

I'm struggling to reproduce this. For me, it behaves like expected, producing `statement {`blocks like in the [test fixtures](https://github.com/flosell/iam-policy-json-to-terraform/tree/master/converter/fixtures). 

Could you let me know which version and which platform you are using and post a sample JSON that reproduces the behaviour for you? 
If you have a bit more time, you could also try [setting up the code on your machine](https://github.com/flosell/iam-policy-json-to-terraform#local-development) (you'll need golang installed) and see if the test pass and/or if you can reproduce the behaviour on a clean build, just to see if this has something to do with your environment or the build you are using.

**Comment by migueleliasweb** [comment] 2020-03-30 23:37
Here @flosell , I will try to get a better example and the versions of the binaries. I will let you know shortly.

**Comment by flosell** [comment] 2020-05-16 09:57
Hi @migueleliasweb any luck making this more reproducible?

**Comment by migueleliasweb** [comment] 2020-05-16 13:04
Sorry @flosell , I don't have that example at han anymore. Let's close this for now....if anyone stumble across this then we can reopen this issue ;).

**Comment by k8s-class** [comment] 2020-06-26 18:54
Doing the same thing for me 
```cat autoscaling.json | iam-policy-json-to-terraform
data "aws_iam_policy_document" "policy" {
  statement = [
    {
      sid       = ""
      effect    = "Allow"
      resources = ["*"]

      actions = [
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:DescribeAutoScalingInstances",
        "autoscaling:SetDesiredCapacity",
        "autoscaling:TerminateInstanceInAutoScalingGroup",
        "autoscaling:DescribeTags",
      ]
    },
  ]
}
```

**Comment by flosell** [comment] 2020-06-27 04:49
Hi @k8s-class, thanks for re-opening this!

As in my [previous reply](https://github.com/flosell/iam-policy-json-to-terraform/issues/9#issuecomment-606012070), could you provide a few details for me to reproduce this (input JSON, version and platform, ...)?

**Comment by kragniz** [comment] 2020-07-28 15:51
@flosell 

```
$ go get github.com/flosell/iam-policy-json-to-terraform
$ iam-policy-json-to-terraform -version
1.5.0
$ curl -s https://kubernetes-sigs.github.io/aws-alb-ingress-controller/examples/iam-policy.json | iam-policy-json-to-terraform | head
data "aws_iam_policy_document" "policy" {
  statement = [
    {
      sid       = ""
      effect    = "Allow"
      resources = ["*"]

      actions = [
        "acm:DescribeCertificate",
        "acm:ListCertificates",
```

Platform information:

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/x/.cache/go-build"
GOENV="/home/x/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/x/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build870253332=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by flosell** [comment] 2020-07-29 01:29
Thank you @kragniz, was able to reproduce the issue using your instructions! Looks like this happens when installing with `go get` but doesn't happen when using the compiled binary from GitHub. 

I'll look into the issue but until that's fixed, the binary from GitHub should be a workaround for you: 

```
$ curl -sL https://github.com/flosell/iam-policy-json-to-terraform/releases/download/1.5.0/iam-policy-json-to-terraform_amd64 > iam-policy-json-to-terraform
$ chmod +x iam-policy-json-to-terraform
$ ./iam-policy-json-to-terraform --version
1.5.0
$ curl -s https://kubernetes-sigs.github.io/aws-alb-ingress-controller/examples/iam-policy.json | ./iam-policy-json-to-terraform | head
data "aws_iam_policy_document" "policy" {
  statement {
    sid       = ""
    effect    = "Allow"
    resources = ["*"]

    actions = [
      "acm:DescribeCertificate",
      "acm:ListCertificates",
      "acm:GetCertificate",
```

**Comment by flosell** [comment] 2020-08-02 04:15
Hi everyone! Turns out I was depending on a branch in a fork of one of the dependencies (hclencoder) and that behaved differently between `go get` and my local and CI builds... 

I'll spend some time looking into why I didn't upstream these patches in the first place and depend on the main library. 

As for the issue you folks reported, that should be fixed: 

```
$ go get github.com/flosell/iam-policy-json-to-terraform
$ iam-policy-json-to-terraform -version
1.5.0
$ curl -s https://kubernetes-sigs.github.io/aws-alb-ingress-controller/examples/iam-policy.json | iam-policy-json-to-terraform | head
data "aws_iam_policy_document" "policy" {
  statement {
    sid       = ""
    effect    = "Allow"
    resources = ["*"]

    actions = [
      "acm:DescribeCertificate",
      "acm:ListCertificates",
      "acm:GetCertificate",
```

Any issues remaining, feel free to reopen this issue.

**Closed by flosell** 2020-08-02 04:15 UTC

**Comment by nitrocode** [comment] 2020-08-02 13:34
@flosell  Can a new version be released since it's a bug fix? Maybe `1.5.1` ?

**Comment by flosell** [comment] 2020-08-02 13:45
Hi @nitrocode, as far as I'm aware, it's only an issue when installing with `go get` which pulls the latest commit from GitHub so shouldn't need a release. 
If I'm missing something there, let me know. Happy to cut a release then.

**Comment by nitrocode** [comment] 2020-08-02 13:49
Oh I see so it only affects people downloading the latest source and not the current release at all. I thought it had something to do with a bad dependency and so I was considering upgrading but now I realize I don't need to.

Thanks for clarifying.
