### ISSUE TITLE
Not parsing correctly adding this statement = [

### ISSUE THREAD

**Issue by k8s-class** [flosell/iam-policy-json-to-terraform#17] opened 2020-06-26 18:58 UTC
Doing the same thing for me 
```cat autoscaling.json | iam-policy-json-to-terraform
data "aws_iam_policy_document" "policy" {
  statement = [
    {
      sid       = ""
      effect    = "Allow"
      resources = ["*"]

      actions = [
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:DescribeAutoScalingInstances",
        "autoscaling:SetDesiredCapacity",
        "autoscaling:TerminateInstanceInAutoScalingGroup",
        "autoscaling:DescribeTags",
      ]
    },
  ]
}
```
Error message

An argument named "statement" is not expected here. Did you mean to define a
block of type "statement"?

_Originally posted by @k8s-class in https://github.com/flosell/iam-policy-json-to-terraform/issues/9#issuecomment-650341601_

**Comment by flosell** [comment] 2020-08-02 04:16
Duplicate of #9 which has been fixed now.

**Closed by flosell** 2020-08-02 04:16 UTC
